### ISSUE TITLE
In swagger docs, missing parameters for UPDATE Dashboard.

### ISSUE THREAD

**Issue by smitesh-cfx** [cloudfabrix/api-postman#11]

**Comment by Rajulkr** [comment]
@srikrishna-cfx to add details on fix and move to dev complete

**Comment by srikrishna-cfx** [comment]
Raised PR,
[https://bitbucket.org/cloudfabrix/saas-portal/pull-requests/285](url)

**Comment by Rajulkr** [comment]
@smitesh-cfx any update in testing ?

**Comment by smitesh-cfx** [comment]
tested it, working fine @Rajulkr
