### ISSUE TITLE
Organization delete api is failing, as it's trying to delete only org with id "efd71fab-0db1-4261-b758-a8c0c55bb726"

### ISSUE THREAD

**Issue by smitesh-cfx** [cloudfabrix/api-postman#20]
1. added the org 
url = "/api/v2/organizations"
data = {
  "description": "Automation Org",
  "name": "api_organization",
  "tag": "CFX-API-AUTO"
}

2. delete org
url = "/api/v2/organizations/organization/{org_id}"

error: {
  "detail": "Failed with remote exception: Failed to delete organization Organization efd71fab-0db1-4261-b758-a8c0c55bb726 doesn't exist"
}

* given any org id to be deleted, the api is trying to delete the same org id "efd71fab-0db1-4261-b758-a8c0c55bb726".
* "organization" is repeated 2 time in the below error

**Comment by srikrishna-cfx** [comment]
PR, [https://bitbucket.org/cloudfabrix/cfx-library-modules/pull-requests/2059](url)

**Comment by Rajulkr** [comment]
@smitesh-cfx to test

**Comment by smitesh-cfx** [comment]
@Rajulkr , @gopalkpd tested and working fine, thank you
