### ISSUE TITLE
user_group update api is not working.

### ISSUE THREAD

**Issue by smitesh-cfx** [cloudfabrix/api-postman#21]
1. added the user_group

data = {       
        "chatbot_policy": "policy",
        "description": "MSP admin Added",
        "name": f"{unique_id}_user_group",
        "profile": "msp-admin",
        "selection_type": "tabular_report",
        "projects": [
            {
                "customerName": f"{c_name}",
                "customerId": f"{c_id}"
            }
        ],
        "tenantId":f"{tenentId}"
    }
 
2. updated the user_group description

data = {
  "profile": "msp-admin",
  "tenantId": "6e3e3b4c-2c6c-4c43-9e95-47522e2b0604",
  "description": "updated",
  "projects": [
    {
      "customerId": "b678c212-4f0c-11ef-b699-0242c0a88006",
      "customerName": "OIA-CloudFabrix"
    }
  ],
  "selection_type": "tabular_report"
}

3. get the user_group 

result = {
      "tenantId": "6e3e3b4c-2c6c-4c43-9e95-47522e2b0604",
      "name": "test_api_20240806135754_user_group",
      "description": null,
      "contactEmail": null,
      "tags": [],
      "project_cfxql": "",
      "projects": "b678c212-4f0c-11ef-b699-0242c0a88006",
      "status": "Active",
      "profile": "msp-admin",
      "createdAt": "2024-08-06T10:03:32",
      "project_names": "OIA-CloudFabrix",
      "role": "msp-admin",
      "chatbot_policy": null
    }

* the description is null and not been updated, similarly tried for chatbot_policy, and contactEmail.

**Comment by gopalkpd** [comment]
PRs:
https://bitbucket.org/cloudfabrix/saas-portal/pull-requests/303
https://bitbucket.org/cloudfabrix/cfx-library-modules/pull-requests/2062

@smitesh-cfx description and chatbot_policy are now updated properly. contactEmail is not supported. Even UI doesn't allow contactEmail in Add and Edit.

**Comment by Rajulkr** [comment]
@smitesh-cfx to test

**Comment by smitesh-cfx** [comment]
@Rajulkr , @gopalkpd  tested and working fine. thank you
